os:
  - linux

language: cpp

sudo: required
services:
  - docker

before_install:
  - docker pull thecruel/cpp3ds

script:
  - mkdir build
  - docker run --rm -v "$PWD":/usr/project -w /usr/project/build thecruel/cpp3ds bash -c "cmake ..; make -j4"
